### PR TITLE
Updated view management and linter

### PR DESCRIPTION
**Pull request by cdavidjean**
- Moved to linter 2.0
- Redid custom view management to use the atom views
  * Type Hierarchy
  * Plugin status
  * References
  * Debugger
  * Run Console (bottom)

### CODE REVIEW

**Comment by devoncarew** [comment]
@cdavidjean, thanks for this PR! I'll take a look at it later today. In the meantime, can you update from the latest from the main repo to resolve the conflicts?

**Comment by cdavidjean** [comment]
I don't know how it happened, but now I have no idea how to solve this?

This branch is 9 commits ahead, 2 commits behind dart-atom:master.

There's no merge option I can find (I'm halfway through reading git for
dummies -- but I have used version control software so much better than
this...)

**Comment by devoncarew** [comment]
Git can be rough, no doubt about it. It's taken me awhile to get right by git. When using it early on, my resource for many situations was to rm -rf the repo and start over :(

Can you list the remotes you have for this repo (`git remote -v`)?

**Comment by cdavidjean** [comment]
djean@djeanz440:~/github/dartlang$ git remote -v
dart-atom https://github.com/dart-atom/dartlang (fetch)
dart-atom https://github.com/dart-atom/dartlang (push)
origin git@github.com:cdavidjean/dartlang (fetch)
origin git@github.com:cdavidjean/dartlang (push)
djean@djeanz440:~/github/dartlang$

Thanks for your help, I'll get it right someday ;)

**Comment by cdavidjean** [comment]
I create a clean folder and pulled and merge both masters (this and mine) and console.dart ended up, after manual merging, be the same as the one in my master.  It seems that accepting my copy of console.dart would be the 'merge' ?

**Comment by devoncarew** [comment]
Hmm, not sure why that would be. These steps might help you out:

- clone the upstream repo to a new dir: `git clone https://github.com/dart-atom/dartlang`
- cd to that dir (dartlang)
- git remote rename origin upstream
- git remote add origin https://github.com/cdavidjean/dartlang
- git fetch origin
- git checkout origin/master
- git branch -b view_management
- git checkout master
- git pull
- git checkout view_management
- git merge master (there may be some manual merging required here)
- git push origin view_management

Then, from the github UI, you should have the option of creating a new PR, from cdavidjean:view_management into upstream:master. Any changes on the view_management branch (from review changes) can continue to be pushed to your origin fork via `git push origin view_management`. After it's merged, you can `git checkout master` and `git pull`. That will actually pull from the upstream repo (the main one) because of the initial rename.

Ping me if you have any issues :)

**Pull request closed without merging**
