### PR TITLE
allow ~ in both Dart and Dartino SDK pref paths

### PR DESCRIPTION
**Pull request by danrubel**
@devoncarew

### CODE REVIEW

**Comment by danrubel** [comment]
Tests fail. Reworking based upon https://github.com/dart-atom/atom.dart/pull/44

**Comment by danrubel** [comment]
Reworked... PTAL
@devoncarew

**Comment by devoncarew** [comment]
lgtm

**Comment by danrubel** [comment]
Merged https://github.com/dart-atom/dartlang/commit/1de5949f2357385985591cfad05c175cd77e8642

**Pull request closed without merging**
