### PR TITLE
rev to 0.2.3

### LINKED ISSUE #36: we need to keep our changelog updated
We need to keep our changelog updated - it's viewable from the preference page.

### PR DESCRIPTION
**Pull request by devoncarew**
fix #36 

@sethladd, can you land this and push a new version of the plugin?

### CODE REVIEW

**Comment by sethladd** [comment]
Let's land https://github.com/dart-atom/dartlang/pull/42 and then we'll publish.

**Comment by devoncarew** [comment]
Reverted the package.json changes; landing.

**Comment by radicaled** [comment]
`apm publish` handles tagging versions; maybe you should rely on that when you're ready to launch?

`apm publish {major|minor|patch}`

**Comment by devoncarew** [comment]
Yup, Seth let me know I shouldn't be manually reving the package version. Would like to figure out some system for keeping the pubspec and changelog versions in sync.

**Comment by radicaled** [comment]
We have grindr, maybe copy the apm flow:

`dart tool/grind.dart publish $version`
==> dirty check, explode if tree is dirty
==> parse package.json, get `$parsedVersion`
==> increment `$parsedVersion` => `$newVersion`, update pubspec.yaml, update package.json
==> updates `CHANGELOG.md`, replaces "# Upcoming Version" ==> "# $newVersion"
==> `git commit -a -m "foo bar"`
==> `git tag $newVersion`
==> `git push -t`
==> `apm publish -t $version`

**Pull request merged**
