### PR TITLE
Use full URL for screenshot

### PR DESCRIPTION
**Pull request by michaelsanford**
Replaced relative with full URL for the screenshot in the README to make it visible on https://atom.io/packages/dartlang

(Currently it shows a broken image.)

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks!

Will that url display the image, or a link to the page for that file? Perhaps update to the raw url:

https://raw.githubusercontent.com/dart-atom/dartlang/master/assets/dart-plugin-atom-screenshot.png

**Comment by michaelsanford** [comment]
It should display the image directly (it did in my test and my preview). But I do recall the content-type header issue of using github directly.

I'll rebase and update the pull request right now :+1:

**Comment by michaelsanford** [comment]
@devoncarew I rebased and pushed your (quite correct) suggestion as 9a0dae6.

**Comment by devoncarew** [comment]
lgtm - thanks for the PR!

**Comment by michaelsanford** [comment]
:+1: thanks for a great plugin!

**Pull request merged**
