### PR TITLE
add support for flutter run/build modes

### PR DESCRIPTION
**Pull request by devoncarew**
Add support for running flutter apps in the three build modes (debug, profile, release) (fix https://github.com/flutter/flutter/issues/4042).

screen shot 2016-06-06 at 4 27 41 pm

@danrubel

### CODE REVIEW

**Comment by danrubel** [comment]
LGTM

**Comment by sethladd** [comment]
Nice! how do I control this in my YAML launch config?

**Comment by devoncarew** [comment]
It's controlled through the toolbar GUI. Thinking about it, the state seemed more transient - per user, and not something you'd necessarily check in to scm.

**Comment by devoncarew** [comment]
It's available in the latest release to try out -

**Comment by sethladd** [comment]
> not something you'd necessarily check in to scm.

True. Should we remove `debug: true` from main.yaml then? Also, I thought we were ignoring `.atom` directory anyway? I always assumed that file shouldn't be checked in.

**Comment by devoncarew** [comment]
Yup, re: removing debug: true.

We do exclude the .atom dir for the flutter project we create, but in general I think launch configs should be sharable between users. They should describe the application to launch - the type of app, the path to the main file, ... . Other launch settings, like debug/release, are more ephemeral.

**Pull request merged**
