### PR TITLE
Inline local var refactoring - fixes #595

### LINKED ISSUE #595: cleap up the clean up the editor context menu contributions
either organize the refactorings into their own menu category, or split the dart contributions into 2 ~equal sized groups.

### PR DESCRIPTION
**Pull request by danrubel**
@devoncarew 
- hook up inline local var refactoring
- extract refactorings into submenu

### CODE REVIEW

**Comment by devoncarew** [comment]
Can you add a screenshot of what the new context menu looks like?

lgtm

**Comment by devoncarew** [comment]
(also, we should update the changelog to include info about the new refactoring)

**Comment by danrubel** [comment]
Good idea. Here's the submenu screenshot and I'll update the change log once your PR lands

image

**Comment by devoncarew** [comment]
Looks nice :)

**Pull request merged**
