### PR TITLE
optionally run server from source

### PR DESCRIPTION
**Pull request by danrubel**
@devoncarew

### CODE REVIEW

**Comment by devoncarew** [comment]
lgtm!

**Comment by kasperpeulen** [comment]
wow, that would be nice

if this land, can I then use it like this?
image

@danrubel @devoncarew

**Comment by danrubel** [comment]
Yes :)`

**Comment by kasperpeulen** [comment]
It works, I can now run my patched analysis server in atom :D
image

**Comment by devoncarew** [comment]
I'm curious, what are you patching it for?

**Comment by kasperpeulen** [comment]
@devoncarew I was writing a PR, for some fix I really wanted to have:
https://github.com/dart-lang/sdk/pull/25099

I made a test, but I also like to see how it works out in a real editor :) 

With this PR, this is now so easy. If I restart the analyzer, it directly works in Atom, I don't even have to restart Atom.

**Pull request merged**
